apiVersion: v1
kind: ConfigMap
metadata:
  name: router-service-config
  labels:
    {{- include "router-service.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config.data | indent 4 }}
